name: Roq Site Deploy

on:
  push:
    branches: [ main ]   # Switch to the branch which should be deployed to S3
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: 'maven'

      - name: Generate Roq Site
        run: QUARKUS_ROQ_GENERATOR_BATCH=true mvn -B package quarkus:run

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3
        run: aws s3 sync ./target/roq s3://quarkus.guru --delete
